### ISSUE TITLE
figure and table environment

### ISSUE THREAD

**Issue by kn1cht** [textlint/textlint-plugin-latex2e#1]
figure環境とtable環境を使用するLaTeXソースでも使用したいです。

- figure環境は`ASTNodeTypes.Image`に該当します
- table環境はASTNodeTypesには定義されていませんが、[textlint AST explorer](https://textlint.github.io/astexplorer/)で確認したところ`Table -> TableRow -> TableCell -> Str`の順に分解するようです

ソースを少し拝見しましたが、parsimmonの使い方などをよく理解できていないため、ひとまず要望のみ出しておきます。

**Comment by ta2gch** [comment]
ご報告ありがとうございます。
もし、文法を追加するのであれば
figure環境はParsimmonのASTからTextlintのASTへ変換する以下のコードの最中で環境名に応じて分岐すればすぐに対応できると思います。https://github.com/ta2gch/textlint-plugin-latex2e/blob/08d22040b7cf774729cc296d8125a39ae06ee8ab/src/latex-to-ast/index.ts#L133-L177
table環境についてはLaTeXの文法だけではなくtable環境のみで有効になる文法があるので、
imtemize環境のように別のパーサーオブジェクトを組み立てて実行する方法が良いと思います。https://github.com/ta2gch/textlint-plugin-latex2e/blob/08d22040b7cf774729cc296d8125a39ae06ee8ab/src/latex-to-ast/environment/list.ts#L23-L47

**Comment by fgborges** [comment]
テーブル環境が未対応ということをメモしておきます。（テーブル環境は自由度が高いので、将来に渡って実装難易度が高そうですが。）

**Comment by tani** [comment]
長くなりましたが、v1.0.0以降からサードパティのパーサーを使用することになりましたので、問題が解決されたとしてクローズします。ありがとうございました。

**Comment by kn1cht** [comment]
ありがとうございました！
