### ISSUE TITLE
v1.1.2 seems not to work

### ISSUE THREAD

**Issue by pddg** [textlint/textlint-plugin-latex2e#140]
## Environment

- Ubuntu 20.04.2 LTS
- Node v14.16.1
- textlint-plugin-latex2e v1.1.2
- textlint v11.9.0
- textlint-rule-sentence-length v2.2.0

## How to reproduce

```bash
$ mkdir latex2e-not-work && cd latex2e-not-work
$ npm init -y && npm install --save \
    textlint@11.9.0 \
    textlint-rule-sentence-length@2.2.0 \
    textlint-plugin-latex2e@1.1.2
$ cat << EOF > sample.tex
\begin{document}
sample source
\end{document}
EOF
$ cat << EOF > .textlintrc
{
    "plugins": ["latex2e"],
    "rules": {"sentence-length": true}
}
EOF
$ npx textlint sample.tex
```

## Expected behavior

It works well and no problems are detected.

## Actual behavior

textlint says `"Failed to load textlint's plugin module: "latex2e" is not found."`.

```bash
$ npx textlint sample.tex
✖ Error
Failed to load textlint's plugin module: "latex2e" is not found.
See FAQ: https://github.com/textlint/textlint/blob/master/docs/faq/failed-to-load-textlints-module.md


✖ Stack trace
ReferenceError: Failed to load textlint's plugin module: "latex2e" is not found.
See FAQ: https://github.com/textlint/textlint/blob/master/docs/faq/failed-to-load-textlints-module.md

    at TextLintModuleResolver.resolvePluginPackageName (/home/pudding/Factory/latex2e-not-work/node_modules/textlint/lib/engine/textlint-module-resolver.js:95:19)
    at TextLintModuleLoader.loadPlugin (/home/pudding/Factory/latex2e-not-work/node_modules/textlint/lib/engine/textlint-module-loader.js:101:43)
    at /home/pudding/Factory/latex2e-not-work/node_modules/textlint/lib/engine/textlint-module-loader.js:91:23
    at Array.forEach (<anonymous>)
    at TextLintModuleLoader.loadFromConfig (/home/pudding/Factory/latex2e-not-work/node_modules/textlint/lib/engine/textlint-module-loader.js:90:28)
    at TextLintEngine.AbstractTextLintEngine (/home/pudding/Factory/latex2e-not-work/node_modules/textlint/lib/engine/textlint-engine-core.js:98:27)
    at new TextLintEngine (/home/pudding/Factory/latex2e-not-work/node_modules/textlint/lib/textlint-engine.js:26:47)
    at Object.executeWithOptions (/home/pudding/Factory/latex2e-not-work/node_modules/textlint/lib/cli.js:203:26)
    at Object.execute (/home/pudding/Factory/latex2e-not-work/node_modules/textlint/lib/cli.js:104:25)
    at /home/pudding/Factory/latex2e-not-work/node_modules/textlint/bin/textlint.js:37:20
```

textlint-plugin-latex2e is installed successfully.

```bash
$ ll -d node_modules/textlint-plugin-latex2e/
drwxr-xr-x 6 pudding pudding 4096 May  8 11:06 node_modules/textlint-plugin-latex2e/
```

textlint-plugin-latex2e@1.1.0 works well.

```
$ npm install --save textlint-plugin-latex2e@v1.1.0
npm WARN latex2e-not-work@1.0.0 No description
npm WARN latex2e-not-work@1.0.0 No repository field.

+ textlint-plugin-latex2e@1.1.0
removed 1 package, updated 2 packages and audited 245 packages in 1.528s

46 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

$ npx textlint sample.tex
$ echo $?
0
```

**Comment by kn1cht** [comment]
I also reproduced this issue.
It seems that v1.1.2 does not have `index.js` in lib/ directory. It has been moved to `lib/src/index.js` and the 'main' script in `package.json` remains `lib/index.js`.

v.1.1.2
![image](https://user-images.githubusercontent.com/16277200/117522745-0b358200-aff0-11eb-9a7e-c43db08ca2fd.png)

v.1.1.0
![image](https://user-images.githubusercontent.com/16277200/117522849-7717ea80-aff0-11eb-9006-e36da36d46c2.png)

**Comment by pddg** [comment]
Do you think that just rewriting `lib/index.js` in package.json to `lib/src/index.js` will work?

**Comment by kn1cht** [comment]
> Do you think that just rewriting `lib/index.js` in package.json to `lib/src/index.js` will work?

It worked 🙂 

I also found the reason why `index.js` had been moved to `lib/src`.

Commit https://github.com/textlint/textlint-plugin-latex2e/commit/e5288b99f59368f369595e14f16a6ce57a5ed6f7 (included in PR #67 ) changed tsconfig.json not to exclude `test` directory and `tsc` builds both of `src/***.ts` and `test/***.ts` into `lib/`.
@pddg  Is this intended behavior? (In other words, should test scripts also be built and included in the npm package?)

**Comment by pddg** [comment]
Oh... I think it is my mistake. There is no need to include test files in the npm package.

**Comment by kn1cht** [comment]
I added "test" to exclude list and confirmed that `lib` has the same structure as v.1.1.0.
I'm preparing PR for this.

```
  "exclude": [
    ".git",
    "node_modules",
    "test"
  ]
````
