### ISSUE TITLE
Renovate and dependabot are conflicted

### ISSUE THREAD

**Issue by pddg** [textlint/textlint-plugin-latex2e#148]
Now we use Renovate as a dependency updater. It will report security issues, too.
However, Dependabot still reports security issues.

For example:

https://github.com/textlint/textlint-plugin-latex2e/pull/146
https://github.com/textlint/textlint-plugin-latex2e/pull/145

**Comment by pddg** [comment]
@tani @kn1cht 
Can I disable dependabot?

**Comment by kn1cht** [comment]
Renovate seems working well, so I agree to disable dependabot

**Comment by tani** [comment]
I thibk so

**Comment by pddg** [comment]
I disabled dependabot and closed duplicated PRs.
