### ISSUE TITLE
`document` environment is parsed as Paragraph

### ISSUE THREAD

**Issue by pddg** [textlint/textlint-plugin-latex2e#28]
refs #27 

> sentence-lengthはParagraphノードがあるとその下の文字列の長さを見るようです。
> 
> https://github.com/textlint-rule/textlint-rule-sentence-length/blob/d8b63e40665e9a745290b06917668f5294aa175e/src/sentence-length.js#L42-L47
> 
> 本家のmarkdown-to-astはCodeBlockをParagraphの下に置かない（textlint AST explorerで適当なコードブロックを入力すればわかります）のに対して、plugin-latex2eはdocument環境をParagraphに変換してしまうのでsentence-lengthの対象となってしまうようです

**Comment by fgborges** [comment]
latex-utensilsを使用したバージョンの開発を進める予定です。
このバージョンでは、すでにCommentノードを構文木レベルで調整する必要があることが既知の問題としてありました。このような構文木の操作と併せて、この問題も解決しましょう。

一方で現行バージョンでの修正PRも歓迎しますが、これに私たちは取り組まずlatex-utensils版の開発に集中しましょう。

**Comment by nzt** [comment]
DONE by #38
