### ISSUE TITLE
Only the first node is parsed, otherwise not.

### ISSUE THREAD

**Issue by pddg** [textlint/textlint-plugin-latex2e#37]
### 問題

例えば

```tex
\begin{equation}
  x^2 - 6x + 1 = 0
\end{equation}
```

は正しく以下の様にパースされますが，

```javascript
{
  loc: { start: { line: 1, column: 0 }, end: { line: 3, column: 14 } },
  range: [ 0, 48 ],
  raw: '\\begin{equation}\nx^2 - 6x + 1 = 0\n\\end{equation}',
  value: 'x^2-6x+1=0',
  type: 'CodeBlock'
}
```

以下の様な場合にでも上記と完全に同じパース結果が返ります．

```tex
\begin{equation}
  x^2 - 6x + 1 = 0
\end{equation}
\begin{equation}
  x^2 - 6x + 1 = 0
\end{equation}
```

### 原因

以下の行で最初のノードのみを返すため，そのTeXソースがフラットな構造で複数のノードを持つ場合，2つ目以降が返されません．

https://github.com/textlint/textlint-plugin-latex2e/blob/0e6629a362aa585dae023f4af51ab82920876aa5/src/latex-to-ast.ts#L413

### 対処法

現状rootノードは無視され，それ以下のノードのみ見て最初の一つだけを返す．ルートが必ず1つのDocumentノードになる必要があるが，LaTeXではパース結果が必ずしもそうであるとは限らない．例えば`\input{}`などを使って読み込む完全でないTeXソースの場合など，`document`がなく，`clean`関数によって削除されないノードが最上位階層にフラットに展開される場合が存在する．

行うべき対応は以下の通り

- cleanによって返されるノードを一つに限定せず全て返す
- 常にDocumentノードがルートとなるようにし，パース結果はその子要素とする

### 懸念点

Documentノードがネストする可能性がある．textlintのASTがこれを許容するのか知りたい．

**Comment by pddg** [comment]
これに関連して，`document`よりも前，または後に書かれたコメントをうまくマッピングすることができません．

**Comment by pddg** [comment]
refs #36

**Comment by nzt** [comment]
DONE by #38
