### ISSUE TITLE
Run test in offline environment

### ISSUE THREAD

**Issue by tani** [textlint/textlint-plugin-latex2e#39]
textlint-rule-ginger uses Ginger API provided by Ginger.
We need to run tests with the internet connect because the rule calls API with HTTP protocol.
We should replace tests with other rules such as textlint-rule-spelling.

**Comment by pddg** [comment]
@tani 
The CI seems to be failed. 
https://github.com/textlint/textlint-plugin-latex2e/actions/runs/559749401
https://github.com/textlint/textlint-plugin-latex2e/actions/runs/559746784

If possible, it would be safer if you could create a PR instead of a push to master :)

**Comment by tani** [comment]
OMG, you're right.
