### ISSUE TITLE
TypeError is occurred if `Parbreak` node appears before the first appearance of actual sentence

### ISSUE THREAD

**Issue by pddg** [textlint/textlint-plugin-latex2e#42]
## 環境

- textlint-plugin-latex2e v1.0.0-alpha.1
- latex-utensils 2.0.0-beta.4

## 問題

```
    TypeError: Cannot read property 'loc' of undefined

      43 |         loc: {
      44 |           start: {
    > 45 |             line: paragraph[0].loc.start.line,
         |                                ^
      46 |             column: paragraph[0].loc.start.column
      47 |           },
      48 |           end: {

      at paragraphize (src/latex-to-ast.ts:45:32)
      at Object.exports.parse (src/latex-to-ast.ts:106:5)
      at Object.<anonymous> (test/latex-to-ast.test.ts:106:20)
```

## 再現方法

document内に文章が出現するよりも前の位置に空行が存在するLaTeXコードをパースする。

```
\documentclass{article}

\begin{document}
  \begin{abstract}
    abcd
  \end{abstract}
\end{document}
```

他に以下の場合も同様。

```
\documentclass{article}
\begin{document}

  \begin{abstract}
    abcd
  \end{abstract}
\end{document}
```

## 原因

```
\documentclass{article}

\begin{document}
  \begin{abstract}
    abcd
  \end{abstract}
\end{document}
```

上記のようなLaTeXコードはlatex-utensilsによって以下の様にパースされます。

```javascript
{
  kind: 'ast.root',
  content: [
    {
      kind: 'command',
      name: 'documentclass',
      args: [Array],
      location: [Object]
    },
    { kind: 'parbreak', location: [Object] },
    {
      kind: 'env',
      name: 'document',
      args: [],
      content: [Array],
      location: [Object]
    }
  ],
  comment: []
}
```

normalize関数を通した後も依然としてParbreakはdocument environmentまたはabstract environmentよりも前に出現した状態でparagraphize関数へ渡されます。

このとき、他のノードよりも先にParbreakが存在するため、以下の行で宣言されているparagraphというアレイが空の状態でアクセスすることになり、undefinedの要素へのアクセスとなり上記エラーが発生します。

https://github.com/textlint/textlint-plugin-latex2e/blob/e75c997fa659c60df4f5cd3ae321853c40bab13b/src/latex-to-ast.ts#L37

**Comment by nzt** [comment]
ご報告ありがとうございます。根本原因として配列の境界エラーをまともに取りあつかってこなかったツケが今になって回ってきているということなので、素直に境界エラー判定のある配列アクセスメソッド(C++の`at`のようなもの)を使用して堅実なものにリプレースしようとおもいます。
ついでに`fp-ts`を使って、エラーをコンパイル段階で特定できる部分を増やそうと思います。

**Comment by nzt** [comment]
`fp-ts`を使って必要最低限なパッチを当てました。`fp-ts`自体は、結構クセの強いライブラリなので、今後のためにもドキュメントなり記事なりを読んで頂けますでしょうか? 巷ではv1時代の記事が多いのでv2に対応した記事であることを確認してくださいね。

**Comment by pddg** [comment]
了解です。目を通しておきます。
