### ISSUE TITLE
Raising error "Unexpected node is given. Is the syntax correct?" with 2 lines comment

### ISSUE THREAD

**Issue by nzt** [textlint/textlint-plugin-latex2e#43]
2行のコメントを下記のように入れると、コメントの挿入に失敗するようです。

```tex
\title{x}
%
%
\author{x}
```

```
    Unexpected node is given. Is the syntax correct?

      120 |       // if comment is surrounding by the line break.
      121 |       // But the parbreak becomes null, so this condition does not used.
    > 122 |       throw Error("Unexpected node is given. Is the syntax correct?");
          |             ^
      123 |     }
      124 |   }
      125 |   // If the comment is not inserted, it would be appeared after all nodes.
```

未だ実装を完璧に理解していないので @pddg さんに確認をお願いしたいのですが可能しょうか?

**Comment by pddg** [comment]
ちょうどそれに取り組んでいて、再現が取れたところでした。多少実験しつつ探ってみます。

**Comment by nzt** [comment]
ありがとうございます。お手数をお掛けしますがよろしくお願いします。

**Comment by pddg** [comment]
どうもこのケースではcompleteBlank関数がAST上から消えているコメント行を`Html`ノードとして補完してしまうため、後からコメントを挿入しようとすると競合するようです。

@nzt 
completeBlankよりも前にコメントの補完を行うことで回避出来そうなのですが、何か問題は考えられますか？

**Comment by nzt** [comment]
ひとまず問題は思いつかないですね。あくまで、ノード間のギャップがあるところを埋めるだけの処理なのでそんなに難しいことはしてないので。取り敢えず、順語入れ替えてテストケースを追加してみていただけますか？

**Comment by pddg** [comment]
paragraphize→completeComments→completeBlankの順にしてみましたが、エラーが多数出ているようですね。

https://github.com/textlint/textlint-plugin-latex2e/runs/618051195?check_suite_focus=true#step:4:84

**Comment by pddg** [comment]
completeComments→completeBlank→paragraphizeにしてみてもむしろfailは増えてしまいました。

**Comment by nzt** [comment]
エラー内容的には正解データセットの方が間違っているように見えますが、いかがでしょうか?

**Comment by pddg** [comment]
例えば

```
\\documentclass{article}
% comment
\\begin{document}
abcd
\\end{document}
% comment
```

において`\begin{document}`や\end{document}`が`Html`ノードとしてパース（補完？）されるのは正しい挙動でしょうか？上記の例は

- Comment
- Html
- Paragraph
  - Str
- Html
- Comment

のようにパースされているようなのですが、この変更を加える前には

- Comment
- Paragraph
  - Str
- Comment

としてパースされているようです。

**Comment by nzt** [comment]
これは下記の理由から正しいです挙動です。

- textlintでは、ノード間の座標(line, column, range)に飛びが発生してはいけない。
- textlintでは、ほとんどのルールでHTMLノードは対象外に指定される
- したがって無意味な部分はHTMLノードに包んで隠すべき

そもそもTxtNodeはmarkdownを意図して設計されているので、あまり綺麗なASTは生成できないだろうと妥協しているので気にしなくても良いと思っていますが、もし良い方法が思いつくのであれば、そちらを採用したいです。

**Comment by pddg** [comment]
なるほど。正しい挙動なら大丈夫そうです。あまり綺麗にいきそうにないというのは同意なので、実用的に問題なければ許容するのが良さそうです。
テストケース等修正して後ほどpushします。
