### ISSUE TITLE
Inline math causes significant performance down and error sometimes

### ISSUE THREAD

**Issue by pddg** [textlint/textlint-plugin-latex2e#48]
## Environment

- macOS 11.0.1
- Nodejs 14.11.0
- textlint-plugin-latex2e v1.0.2
- textlint v11.7.6
- textlint-rule-sentence-length v2.2.0

## Sample TeX source

```tex
\documentclass{jarticle}
\begin{document}
    $ x^2 -6x + 1 = 0$
    % repeat the above line
\end{document}
```

<details>
<summary>Entire sources</summary>

```tex
\documentclass{jarticle}
\begin{document}
    $ x^2 -6x + 1 = 0$
    $ x^2 -6x + 1 = 0$
    $ x^2 -6x + 1 = 0$
    $ x^2 -6x + 1 = 0$
    $ x^2 -6x + 1 = 0$
    $ x^2 -6x + 1 = 0$
    $ x^2 -6x + 1 = 0$
    $ x^2 -6x + 1 = 0$
    $ x^2 -6x + 1 = 0$
    $ x^2 -6x + 1 = 0$
    $ x^2 -6x + 1 = 0$
    $ x^2 -6x + 1 = 0$
    $ x^2 -6x + 1 = 0$
    $ x^2 -6x + 1 = 0$
    $ x^2 -6x + 1 = 0$
    $ x^2 -6x + 1 = 0$
    $ x^2 -6x + 1 = 0$
    $ x^2 -6x + 1 = 0$
    $ x^2 -6x + 1 = 0$
    $ x^2 -6x + 1 = 0$
\end{document}
```

</details>

Save that source as `sample.tex`.
And the `.textlintrc` is as follows.

```json
{
    "plugins": ["latex2e"],
    "rules": {
        "sentence-length": true
    }
}
```

## Expected behavior

`luparse`, a command-line utility of latex-utensils parses the sample source within 0.5 sec.

```bash
$ /usr/bin/time -p npx luparse -i -l sample.tex > /dev/null
real         0.35
user         0.12
sys          0.11
```

So the textlint with textlint-plugin-latex2e will be expected to take less than about few seconds at the latest.

## Actual behavior

It takes about 50x times to complete.

```bash
$ /usr/bin/time -p npx textlint math.tex
real       153.24
user       144.01
sys          2.23
```

**Comment by tani** [comment]
Thank you for reporting us. We should check what procedure is called frequently.
I think `ndb` is a good tool to detect such a procedure. Please try it to inspect source deeply.
I also start to check it in my local environment.
