### ISSUE TITLE
Automated publishing

### ISSUE THREAD

**Issue by pddg** [textlint/textlint-plugin-latex2e#58]
## Current problem

- There is no way to publish the module without helping from @tani .
- There is a discrepancy between the version written in `package.json` and the published version of this package.

## How

- Use GitHub Actions to publish.
  - Maybe this article will help us? https://docs.github.com/ja/free-pro-team@latest/actions/guides/publishing-nodejs-packages

### 1.  Use `VERSION` file

Create these files.

- `VERSION`
  - Write the current version in `VERSION`.
- New workflow (`Release`) triggered by pushing the tag (e.g. `v1.0.6`)

If we want to publish the new version of this package, update the version in `VERSION` and create a new pull request. Push a new commit that syncs the version of `VERSION` and the version of `package.json` in GitHub Actions.

After merging, add a new tag to this repo in GitHub Actions automatically if `VERSION` is changed. Next, `Release` workflow is triggered and it publishes the package to npm.

**NOTE**

- How to combine workflows is a difficult problem when you also want to run tests before publishing the package.
  - We have to be careful because we may need to write the same content again in different workflows.
- How to detect the changes in GitHub Actions. https://github.community/t/find-what-files-changed-in-a-pushed-commit/17037/2
- We need to make sure that we can't push to the master branch, and that we can't do a merge without Approve.
  - These restrictions can be achieved with GitHub's features.
  - We can push any tags to this repo even if the restrictions are introduced.

### 2. Use tag

This is a very simple way to do it: only when a tag is pushed, publish will be executed. Other than that, all other jobs in the workflow are the same as in normal CI.

**NOTE**

- This method does not prevent the discrepancy between the version written in `package.json` and the published version of this package.

## Security

We can define an environment in GitHub Actions. Separate secrets from normal CI. We can set it up so that jobs that use those environments require the permission of a specified reviewer to run (currently in beta).

- https://github.blog/changelog/2020-12-15-github-actions-environments-environment-protection-rules-and-environment-secrets-beta/
- https://blog.shibayan.jp/entry/20201217/1608190413

**Comment by pddg** [comment]
@tani @kn1cht 
Do you have any ideas or comments?

**Comment by tani** [comment]
Sounds good. We can use existing package like `release-it`. 
I have no experience such package.

https://devblog.thebase.in/entry/automatic-release-on-github-actions

**Comment by pddg** [comment]
I created a sample repository https://github.com/pddg/test-npm-pkg .

From this experience, I realized that I needed to make some modifications to the design.

- VERSION file is not needed.
  - Use `version` in package.json directly. This is a more simple and declarative way to deploy a new version.
- Do not use `release-it` 
  - `release-it` needs to push a commit that updates `package.json` to the default branch. However, it requires that the branch protection rule is disabled.
  - Using a commit message on how to version up is not clear.
  - Releasing every merge is a big deal when used in conjunction with automatic dependency updates (i.e. Renovate).
- Personal Access Token is needed to trigger a workflow from another workflow.
  - This is a limitation of GitHub Actions. https://docs.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token
  - This is required to push a new tag to the repository.
- Use can-npm-publish before publishing.
  - Refs. https://efcl.info/2018/06/21/can-npm-publish/

Based on these modifications, the sample repository works as follows.

1. The `version` in `package.json` is updated in a topic branch. the PR is created with it.
2. After passing CI, we merge the PR to the default branch (e.g. `master`).
3. `build` workflow is triggered on the default branch and it checks that the version in `package.json` exists in the tags of the repository, create the tag and push it if not exists.
4. `release` workflow is triggered by pushing the tag. It creates a new release on GitHub (i.e. `Release v*.*.*`) and publish the package to npmjs.

@tani @kn1cht 
Any ideas or questions?

**Comment by tani** [comment]
Is it like this?

<div><a href='//sketchviz.com/@tani/f06d0227e96825fd08f06b2ab19e9b61'><img src='https://sketchviz.com/@tani/f06d0227e96825fd08f06b2ab19e9b61/b25e626b209c3e8616313c92316aef5c708c0334.sketchy.png' style='max-width: 100%;'></a><br/><span style='font-size: 80%;color:#555;'>Hosted on <a href='//sketchviz.com/' style='color:#555;'>Sketchviz</a></span></div>

**Comment by tani** [comment]
I ommit creating branch. The workflow is the following.

- The version is available on npm?
- If so, it will be publish after merging it.

That's all. It will work well.

**Comment by pddg** [comment]
@tani 
Sorry for the late reply. And nice work!

However, the merged workflow seems not to be worked.
https://github.com/textlint/textlint-plugin-latex2e/actions/runs/506755786/workflow

It may lack the double quotation around the characters, I think.

**Comment by tani** [comment]
Oops, thank you.

**Comment by pddg** [comment]
It is still failed to run...
https://github.com/textlint/textlint-plugin-latex2e/actions/runs/506984074

Is the double quotation not available?

**Comment by tani** [comment]
Woo hoo!
