### ISSUE TITLE
Automated dependency updating

### ISSUE THREAD

**Issue by pddg** [textlint/textlint-plugin-latex2e#59]
## Current problem

- When a new version of latex-utensils is released, manual work is required to keep up.

## How to resolve

Introduce [Renovate](https://github.com/apps/renovate).
It is free to use for open source project.

## Design proposal

Renovate just create Pull Request only. We review it and accept or reject it.

## What to decide

- How frequently check
- Whether to automatically merge patch version updates
- When to upgrade the version of this package

**Comment by tani** [comment]
Blocked by #58

**Comment by tani** [comment]
We can deploy dependency-bot that is released by GitHub.
It is more reliable, isn't it?

@azu Can we deploy dependency-bot to this repository?

**Comment by azu** [comment]
you can enable dependabot via settings
https://github.com/textlint/textlint-plugin-latex2e/settings/security_analysis

**Comment by tani** [comment]
Thank you! I can do it.

**Comment by tani** [comment]
It seems that the dependabot works fine e.g., #65

**Comment by tani** [comment]
Closed by #76
