### ISSUE TITLE
Branch protection rule

### ISSUE THREAD

**Issue by pddg** [textlint/textlint-plugin-latex2e#68]
## Current problems

- Contributors can merge their PR by themselves even if it does not pass the tests on CI.

## Proposal

- Use branch protection rule
  - Target: `master`
  - Rules
    - Require pull request reviews before merging
      - Dismiss stale pull request approvals when new commits are pushed
    - Require status checks to pass before merging

**Comment by pddg** [comment]
@tani @kn1cht 
If it's not a problem, please react with 👍. I'll set it up.

**Comment by pddg** [comment]
Also, enable the "Automatically delete head branches" option.

**Comment by pddg** [comment]
done

**Comment by tani** [comment]
Thanks!
