### ISSUE TITLE
Parsing error in itemize with newlines

### ISSUE THREAD

**Issue by tani** [textlint/textlint-plugin-latex2e#71]
> itemize中に改行があるとtextlint-plugin-latex2eがパースに失敗してしまうっぽい。

by https://twitter.com/61503891/status/1356798733099274242

**Comment by pddg** [comment]
I could not confirm this issue. It is not reproduced with the following sample sources and textlint-plugin-latex2e@1.0.6.

```tex
\begin{itemize}
    \item item1 \\
          item1 second line
    \item item2
\end{itemize}
```

```tex
\begin{itemize}
    \item item1
          item1 second line
    \item item2
\end{itemize}
```

```tex
\begin{itemize}
    \item item1

    \item item2

\end{itemize}
```

I tried to reproduce it with `description` environment. However, It does not.

**Comment by tani** [comment]
Thank you for checking this issue. He might has misunderstood what it occured. Anyway, we can close this issue because we can not reproduce it.
