### ISSUE TITLE
RFC: Relicesing to MIT

### ISSUE THREAD

**Issue by tani** [textlint/textlint-plugin-latex2e#75]
When we make online textlint playground with this plugin,
GPLv3 license possibly courses problem. I propose to change the license from GPLv3 to MIT.
If you agree with me, comment this thread please because I need to get agreement by **all** contributors.

Contributors, @w0xel @pddg @kn1cht 
Thank you for your contributions!

**Comment by kn1cht** [comment]
I agree!

**Comment by pddg** [comment]
+1

**Comment by tani** [comment]
As @w0xel  looks like an inactive account on GitHub, It takes a long time to take his agreement. 
I will remove his code from this project, and rewrite the own code. His commits are https://github.com/textlint/textlint-plugin-latex2e/commits?author=w0xel .

I have to say thank you, @w0xel. I cannot imagine the success of this project without your contribution!

Related discussion: https://github.com/lerna/lerna/issues/1620

**Comment by w0xel** [comment]
Sorry for the late answer. If you've not yet removed the commits, I also agree to relicensing. In any way, good look with your project!

**Comment by tani** [comment]
@w0xel Thank you!
